apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
spec:
  selector:
    matchLabels:
      app: my-webapp
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myweb-app
    spec:
      containers:
      - name: my-webapp
        image: mukund2618/cap_stone_1
        ports:
        - containerPort: 80

