# Instruction for Dockerfile to create a new image on top of the base image (httpd)

FROM httpd:2.4

MAINTAINER mukund2618@gmail.com

#COPY index.html /var/www/html/

WORKDIR /home/ubuntu/webserver

COPY . .

EXPOSE 80

#ENTRYPOINT echo

CMD echo 'Hello DevOps Engineers, Welcome to my Capstone Project!!!!!'






