apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp-deploy
spec:
  selector:
    matchLabels:
      app: my-webapp
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: my-webapp-container
        image: mukund2618/cap_stone_1
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
spec:
  type: NodePort
  selector:
    app: my-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000

